#!/usr/bin/env sh
set -eu

if grep -Eq '^Release [0-9]+\.[0-9]+\.[0-9]+$' "$1"; then
  exit 0
fi

mise exec -- prek run --stage commit-msg --commit-msg-filename "$1"
bun run lint:commit-message -- "$1"
