[application]
name = "shprd-shell"
default_platform = "web"
out_dir = "crates/shprd-shell/dist"
asset_dir = "server/public"

[web.app]
title = "SHPRD"

[bundle]
identifier = "dev.nebuless.shprd"
publisher = "Nebuless"
