import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { createHash } from "node:crypto";
import { basename, dirname, join, resolve } from "node:path";
import {
  DEFAULT_SERVICE_ENV_FILE,
  escapeSystemdExecPath,
  GENERATED_MARKER,
  LEGACY_GENERATED_MARKER,
  LEGACY_SERVICE_LABEL,
  renderLaunchdService,
  renderSystemdService,
  renderWindowsTaskDefinition,
  resolveServicePaths,
  resolveServicePlatform,
  SERVICE_LABEL,
  type ServicePlatform,
} from "./service-definitions";
import { defaultAuthTokenPath, loadOrCreateAuthToken } from "./auth-token";
import { browserUrlFor, legacyConfigDirForRuntime } from "./server-config";

type ServiceAction = "install" | "uninstall" | "status" | "restart" | "reload";
type TailscaleMode = "token" | "no-auth" | undefined;

export const SERVICE_COMMAND_CONTINUE = Symbol("service-command-continue");

interface ServiceRuntime {
  platform: string;
  homeDir: string;
  appDataDir?: string;
  execPath: string;
  argv: string[];
  uid?: number;
}

type RunCommand = (argv: string[], options?: { quiet?: boolean }) => number;

interface ServiceCommandDependencies {
  runtime?: ServiceRuntime;
  runCommand?: RunCommand;
  getLanIPs?: () => string[];
  getTailscaleIPs?: () => string[];
  isLegacyServiceActive?: (
    platform: ServicePlatform,
    runtime: ServiceRuntime,
  ) => boolean;
  log?: (message: string) => void;
  error?: (message: string) => void;
}

interface ParsedServiceCommand {
  action: ServiceAction | "help" | "run";
  force: boolean;
  tailscaleMode: TailscaleMode;
  configPath?: string;
}

function parseAuthTokenCommand(args: string[]): "show" | "path" | null {
  if (args[0] !== "auth" || args[1] !== "token") return null;
  if (args[2] === "show" || args[2] === "path") {
    if (args.length === 3) return args[2];
    throw new Error(`unknown auth token option: ${args[3]}`);
  }
  if (args.length === 2 || args[2] === "help" || args[2] === "--help") {
    return null;
  }
  throw new Error(`unknown auth token action: ${args[2]}`);
}

function parseServiceCommand(args: string[]): ParsedServiceCommand | null {
  if (args[0] !== "service") return null;
  const tail = args.slice(1);
  if (
    tail.length === 0 ||
    tail[0] === "help" ||
    tail.includes("--help") ||
    tail.includes("-h")
  ) {
    return { action: "help", force: false, tailscaleMode: undefined };
  }

  const action = tail[0];
  if (action === "run") {
    if (tail.length !== 2 || !tail[1]) {
      throw new Error("internal service run requires one environment file");
    }
    return {
      action: "run",
      force: false,
      tailscaleMode: undefined,
      configPath: tail[1],
    };
  }
  if (
    !["install", "uninstall", "status", "restart", "reload"].includes(action)
  ) {
    throw new Error(`unknown service action: ${action}`);
  }
  const options = tail.slice(1);
  const tailscaleMode = options.includes("--tailscale-no-auth")
    ? "no-auth"
    : options.includes("--tailscale")
      ? "token"
      : undefined;
  const unknown = options.filter(
    (option) =>
      option !== "--force" &&
      option !== "--tailscale" &&
      option !== "--tailscale-no-auth",
  );
  if (unknown.length > 0) {
    throw new Error(`unknown service option: ${unknown[0]}`);
  }
  if (
    options.includes("--tailscale") &&
    options.includes("--tailscale-no-auth")
  ) {
    throw new Error("choose only one Tailnet authentication mode");
  }
  if ((options.includes("--force") || tailscaleMode) && action !== "install") {
    throw new Error(
      "service install options are only valid with `service install`",
    );
  }
  return {
    action: action as ServiceAction,
    force: options.includes("--force"),
    tailscaleMode,
  };
}

function serviceHelp(): string {
  return `Manage SHPRD as a user service.

Usage:
  shprd service install [--force] [--tailscale | --tailscale-no-auth]
  shprd service status
  shprd service restart
  shprd service reload
  shprd service uninstall

Linux uses a systemd user service. macOS uses a launchd LaunchAgent.
Windows uses a per-user Task Scheduler task that starts at login.
New services listen on 127.0.0.1 by default.
--tailscale binds exactly one detected Tailnet IPv4 and keeps SHPRD token auth.
--tailscale-no-auth binds exactly one detected Tailnet IPv4 and relies on Tailnet ACLs.
Neither mode changes Tailscale configuration. Install preserves the platform-specific
shprd.env file and starts the service.
Reload re-reads the service definition and restarts the process.
Use --force only to replace an existing service definition not generated by
SHPRD. Uninstall preserves the environment file.
`;
}

function defaultRunCommand(
  argv: string[],
  options: { quiet?: boolean } = {},
): number {
  const result = Bun.spawnSync(argv, {
    stdin: "inherit",
    stdout: options.quiet ? "ignore" : "inherit",
    stderr: options.quiet ? "ignore" : "inherit",
  });
  return result.exitCode ?? 1;
}

function defaultTailscaleIPs(): string[] {
  const result = Bun.spawnSync(["tailscale", "ip", "-4"], {
    stdin: "ignore",
    stdout: "pipe",
    stderr: "ignore",
  });
  if (result.exitCode !== 0) return [];
  return new TextDecoder()
    .decode(result.stdout)
    .split(/\r?\n/)
    .map((address) => address.trim())
    .filter(Boolean);
}

function ensureStandaloneBinary(runtime: ServiceRuntime): string {
  const invoked = runtime.argv[1] ?? "";
  const executable = basename(runtime.execPath).toLowerCase();
  if (
    executable === "bun" ||
    executable === "bun.exe" ||
    invoked.endsWith("src/index.ts")
  ) {
    throw new Error("service install requires the standalone shprd binary");
  }
  return resolve(runtime.execPath);
}

const WINDOWS_TASK_NOT_FOUND_EXIT_CODE = 3;

type WindowsTaskQuery =
  | { status: "exists" }
  | { status: "missing" }
  | { status: "error"; code: number };

function windowsTaskName(paths: { taskName?: string }): string {
  if (!paths.taskName) throw new Error("Windows service task name is missing");
  return paths.taskName;
}

function powershellLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function queryWindowsTask(
  taskName: string,
  runCommand: RunCommand,
): WindowsTaskQuery {
  const task = powershellLiteral(taskName);
  const script = `try { Get-ScheduledTask -TaskName ${task} -ErrorAction Stop | Out-Null; exit 0 } catch { if ($_.FullyQualifiedErrorId -like 'CmdletizationQuery_NotFound_TaskName*') { exit ${WINDOWS_TASK_NOT_FOUND_EXIT_CODE} }; Write-Error $_; exit 1 }`;
  const code = runCommand([
    "powershell.exe",
    "-NoProfile",
    "-NonInteractive",
    "-Command",
    script,
  ]);
  if (code === 0) return { status: "exists" };
  if (code === WINDOWS_TASK_NOT_FOUND_EXIT_CODE) {
    return { status: "missing" };
  }
  return { status: "error", code };
}

function registerWindowsTask(
  definitionPath: string,
  runCommand: RunCommand,
): number {
  return runCommand([
    "powershell.exe",
    "-NoProfile",
    "-NonInteractive",
    "-ExecutionPolicy",
    "Bypass",
    "-File",
    definitionPath,
  ]);
}

function waitForWindowsTaskStop(
  taskName: string,
  runCommand: RunCommand,
): number {
  const task = powershellLiteral(taskName);
  const script = `$deadline = (Get-Date).AddSeconds(15); while ((Get-Date) -lt $deadline) { try { $taskInfo = Get-ScheduledTask -TaskName ${task} -ErrorAction Stop } catch { if ($_.FullyQualifiedErrorId -like 'CmdletizationQuery_NotFound_TaskName*') { exit 0 }; Write-Error $_; exit 1 }; if ($taskInfo.State -ne 'Running') { exit 0 }; Start-Sleep -Milliseconds 100 }; Write-Error 'scheduled task did not stop within 15 seconds'; exit 1`;
  return runCommand([
    "powershell.exe",
    "-NoProfile",
    "-NonInteractive",
    "-Command",
    script,
  ]);
}

function restartWindowsTask(taskName: string, runCommand: RunCommand): number {
  runCommand(["schtasks.exe", "/End", "/TN", taskName], { quiet: true });
  const waitCode = waitForWindowsTaskStop(taskName, runCommand);
  if (waitCode !== 0) return waitCode;
  return runCommand(["schtasks.exe", "/Run", "/TN", taskName]);
}

function assertServiceDefinitionWritable(path: string, force: boolean) {
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (
      !existing.includes(GENERATED_MARKER) &&
      !existing.includes(LEGACY_GENERATED_MARKER) &&
      !force
    ) {
      throw new Error(
        `${path} was not generated by SHPRD; rerun with --force to replace it`,
      );
    }
  }
}

function commandContainsArgument(command: string, argument: string): boolean {
  let offset = 0;
  while (offset < command.length) {
    const index = command.indexOf(argument, offset);
    if (index < 0) return false;
    const before = index === 0 ? "" : command[index - 1];
    const afterIndex = index + argument.length;
    const after = afterIndex >= command.length ? "" : command[afterIndex];
    const hasStartBoundary = before === "" || /\s|["']/.test(before);
    const hasEndBoundary = after === "" || /\s|["']/.test(after);
    if (hasStartBoundary && hasEndBoundary) return true;
    offset = index + argument.length;
  }
  return false;
}

function preservedSystemdExecStart(
  definitionPath: string,
  binaryPath: string,
): string | undefined {
  if (!existsSync(definitionPath)) return undefined;
  const contents = readFileSync(definitionPath, "utf8");
  if (
    !contents.includes(GENERATED_MARKER) &&
    !contents.includes(LEGACY_GENERATED_MARKER)
  ) {
    return undefined;
  }

  const commands = contents
    .split(/\r?\n/)
    .filter((line) => line.startsWith("ExecStart="))
    .map((line) => line.slice("ExecStart=".length).trim())
    .filter(Boolean);
  if (commands.length !== 1) return undefined;

  const command = commands[0];
  const directCommands = new Set([
    binaryPath,
    escapeSystemdExecPath(binaryPath),
    // Recognize the quoted form emitted by herdr-gui <= 0.2.20 so reinstall
    // migrates it instead of treating it as a custom wrapper command.
    `"${binaryPath
      .replaceAll("\\", "\\\\")
      .replaceAll('"', '\\"')
      .replaceAll("%", "%%")}"`,
  ]);
  if (directCommands.has(command)) return undefined;

  // Keep an intentional supervisor wrapper only when it still launches the
  // exact binary being installed. Stale or unrelated commands are replaced.
  return commandContainsArgument(command, binaryPath) ? command : undefined;
}

function writeServiceDefinition(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true });
  const temporaryPath = `${path}.tmp-${process.pid}`;
  try {
    writeFileSync(temporaryPath, content, { mode: 0o644 });
    renameSync(temporaryPath, path);
  } finally {
    rmSync(temporaryPath, { force: true });
  }
}

function ensureEnvironmentFile(path: string): boolean {
  mkdirSync(dirname(path), { recursive: true });
  const created = !existsSync(path);
  if (created) writeFileSync(path, DEFAULT_SERVICE_ENV_FILE, { mode: 0o600 });
  chmodSync(path, 0o600);
  return created;
}

function decodeEnvironmentValue(rawValue: string): string {
  const quote = rawValue[0];
  return rawValue.length >= 2 &&
    (quote === "'" || quote === '"') &&
    rawValue.at(-1) === quote
    ? rawValue.slice(1, -1)
    : rawValue;
}

function readEnvironmentValue(
  contents: string,
  name: string,
): string | undefined {
  let value: string | undefined;
  for (const line of contents.split(/\r?\n/)) {
    const match = line.match(
      new RegExp(`^\\s*(?:export\\s+)?${name}\\s*=\\s*(.*?)\\s*$`),
    );
    if (!match) continue;
    value = decodeEnvironmentValue(match[1] ?? "");
  }
  return value;
}

function loadServiceEnvironmentFile(path: string) {
  const contents = readFileSync(path, "utf8");
  for (const [index, line] of contents.split(/\r?\n/).entries()) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const match = line.match(
      /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/,
    );
    if (!match) {
      throw new Error(`invalid environment entry at ${path}:${index + 1}`);
    }
    process.env[match[1]] = decodeEnvironmentValue(match[2] ?? "");
  }
}

interface ServiceAccess {
  host: string;
  port: number;
  tokenPath: string;
  usesFixedPassword: boolean;
  tailscaleNoAuth: boolean;
}

function prepareServiceAccess(configPath: string): ServiceAccess {
  const contents = readFileSync(configPath, "utf8");
  const host = readEnvironmentValue(contents, "HOST") || "127.0.0.1";
  const configuredPort = readEnvironmentValue(contents, "PORT");
  const port = Number(configuredPort || 8787);
  if (!Number.isInteger(port) || port < 1 || port > 65_535) {
    throw new Error(`invalid PORT in ${configPath}: ${configuredPort}`);
  }
  const tailscaleNoAuth =
    readEnvironmentValue(contents, "SHPRD_TAILSCALE_NO_AUTH") === "1";
  const tailscaleTokenAuth =
    readEnvironmentValue(contents, "SHPRD_TAILSCALE_NO_AUTH") === "0" &&
    isTailnetIPv4(host);
  return {
    host,
    port,
    tokenPath: join(dirname(configPath), "auth-token"),
    usesFixedPassword:
      !tailscaleTokenAuth &&
      (
        readEnvironmentValue(contents, "SHPRD_PASSWORD") ??
        readEnvironmentValue(contents, "HERDR_GUI_PASSWORD") ??
        ""
      ).length > 0,
    tailscaleNoAuth,
  };
}

function printServiceAccess(
  access: ServiceAccess,
  log: (message: string) => void,
) {
  const url = browserUrlFor(access.host, access.port);
  if (access.tailscaleNoAuth) {
    log(`Tailnet URL: ${url}`);
    log(
      "Authentication: Tailnet ACLs control access; SHPRD token auth is disabled",
    );
    return;
  }
  if (access.usesFixedPassword) {
    log("Authentication: fixed password from the service config");
    log(`Open: ${url}`);
    return;
  }
  if (
    access.host === "127.0.0.1" ||
    access.host === "localhost" ||
    access.host === "::1"
  ) {
    log(`Open: ${url} (local access)`);
    return;
  }
  log(`Tailnet URL: ${url}`);
  log("Authentication: SHPRD token required; run `shprd auth token show`");
  log(`Token file: ${access.tokenPath}`);
}

function isTailnetIPv4(ip: string): boolean {
  const match = ip.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/);
  if (!match) return false;
  const octets = match.slice(1).map(Number);
  return (
    octets.every((octet) => octet >= 0 && octet <= 255) &&
    octets[0] === 100 &&
    octets[1] >= 64 &&
    octets[1] <= 127
  );
}

function tailscaleIPv4(resolveTailscaleIPs: () => string[]): string {
  const addresses = [...new Set(resolveTailscaleIPs().filter(isTailnetIPv4))];
  if (addresses.length !== 1) {
    throw new Error(
      "Tailnet install requires exactly one Tailnet IPv4 from `tailscale ip -4`",
    );
  }
  return addresses[0];
}

function isEnvironmentAssignment(line: string, name: string): boolean {
  return new RegExp(`^\\s*(?:export\\s+)?${name}\\s*=`).test(line);
}

function replaceEnvironmentValue(
  contents: string,
  name: string,
  value: string,
): string {
  const retained = contents
    .split(/\r?\n/)
    .filter((line) => !isEnvironmentAssignment(line, name));
  while (retained.at(-1) === "") retained.pop();
  retained.push(`${name}=${value}`, "");
  return retained.join("\n");
}

function removeEnvironmentValue(contents: string, name: string): string {
  const retained = contents
    .split(/\r?\n/)
    .filter((line) => !isEnvironmentAssignment(line, name));
  while (retained.at(-1) === "") retained.pop();
  return `${retained.join("\n")}\n`;
}

function hasEnvironmentValue(contents: string, name: string): boolean {
  return contents
    .split(/\r?\n/)
    .some((line) => isEnvironmentAssignment(line, name));
}

function legacyServiceDefinitionPath(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
): string {
  if (platform === "systemd") {
    return join(
      runtime.homeDir,
      ".config",
      "systemd",
      "user",
      "herdr-gui.service",
    );
  }
  if (platform === "launchd") {
    return join(
      runtime.homeDir,
      "Library",
      "LaunchAgents",
      `${LEGACY_SERVICE_LABEL}.plist`,
    );
  }
  const base = join(
    runtime.appDataDir ?? join(runtime.homeDir, "AppData", "Roaming"),
    "herdr-gui",
  );
  return join(base, "herdr-gui-task.ps1");
}

function legacyWindowsTaskName(runtime: ServiceRuntime): string {
  const base = join(
    runtime.appDataDir ?? join(runtime.homeDir, "AppData", "Roaming"),
    "herdr-gui",
  );
  const userKey = createHash("sha256")
    .update(base.toLowerCase())
    .digest("hex")
    .slice(0, 16);
  return `${LEGACY_SERVICE_LABEL}-${userKey}`;
}

function quietCommandExit(argv: string[]): number | undefined {
  try {
    return Bun.spawnSync(argv, {
      stdin: "ignore",
      stdout: "ignore",
      stderr: "ignore",
    }).exitCode;
  } catch {
    return undefined;
  }
}

function defaultIsLegacyServiceActive(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
): boolean {
  if (platform === "systemd") {
    return (
      quietCommandExit([
        "systemctl",
        "--user",
        "is-active",
        "--quiet",
        "herdr-gui.service",
      ]) === 0
    );
  }
  if (platform === "launchd") {
    return (
      runtime.uid !== undefined &&
      quietCommandExit([
        "launchctl",
        "print",
        `gui/${runtime.uid}/${LEGACY_SERVICE_LABEL}`,
      ]) === 0
    );
  }
  return (
    quietCommandExit([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-Command",
      `try { Get-ScheduledTask -TaskName ${powershellLiteral(legacyWindowsTaskName(runtime))} -ErrorAction Stop | Out-Null; exit 0 } catch { exit 1 }`,
    ]) === 0
  );
}

function assertNoLegacyService(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  isLegacyServiceActive: (
    platform: ServicePlatform,
    runtime: ServiceRuntime,
  ) => boolean,
) {
  const legacyDefinition = legacyServiceDefinitionPath(platform, runtime);
  if (existsSync(legacyDefinition)) {
    throw new Error(
      `legacy herdr-gui service exists at ${legacyDefinition}; uninstall it before installing SHPRD`,
    );
  }
  if (isLegacyServiceActive(platform, runtime)) {
    throw new Error(
      "legacy herdr-gui service is active; stop and uninstall it before installing SHPRD",
    );
  }
}

function installService(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  force: boolean,
  tailscaleMode: TailscaleMode,
  runCommand: RunCommand,
  resolveTailscaleIPs: () => string[],
  isLegacyServiceActive: (
    platform: ServicePlatform,
    runtime: ServiceRuntime,
  ) => boolean,
  log: (message: string) => void,
): number {
  const binaryPath = ensureStandaloneBinary(runtime);
  const tailscaleIp = tailscaleMode
    ? tailscaleIPv4(resolveTailscaleIPs)
    : undefined;
  if (platform === "launchd" && runtime.uid === undefined) {
    throw new Error("cannot determine the current user id for launchd");
  }
  const paths = resolveServicePaths(
    platform,
    runtime.homeDir,
    runtime.appDataDir,
  );
  if (platform === "windows-task") {
    const taskName = windowsTaskName(paths);
    const taskQuery = queryWindowsTask(taskName, runCommand);
    if (taskQuery.status === "error") return taskQuery.code;
    if (
      taskQuery.status === "exists" &&
      !existsSync(paths.definition) &&
      !force
    ) {
      throw new Error(
        `scheduled task ${taskName} already exists; rerun with --force to replace it`,
      );
    }
  }
  assertNoLegacyService(platform, runtime, isLegacyServiceActive);
  assertServiceDefinitionWritable(paths.definition, force);
  const environmentCreated = ensureEnvironmentFile(paths.config);
  let contents = readFileSync(paths.config, "utf8");
  if (tailscaleMode) {
    contents = replaceEnvironmentValue(contents, "HOST", tailscaleIp ?? "");
    contents = replaceEnvironmentValue(
      contents,
      "SHPRD_TAILSCALE_NO_AUTH",
      tailscaleMode === "no-auth" ? "1" : "0",
    );
  } else if (hasEnvironmentValue(contents, "SHPRD_TAILSCALE_NO_AUTH")) {
    contents = replaceEnvironmentValue(contents, "HOST", "127.0.0.1");
    contents = removeEnvironmentValue(contents, "SHPRD_TAILSCALE_NO_AUTH");
  }
  writeFileSync(paths.config, contents, { mode: 0o600 });
  const access = prepareServiceAccess(paths.config);
  if (paths.stdoutLog) mkdirSync(dirname(paths.stdoutLog), { recursive: true });
  const customSystemdExecStart =
    platform === "systemd"
      ? preservedSystemdExecStart(paths.definition, binaryPath)
      : undefined;
  const definition =
    platform === "systemd"
      ? renderSystemdService(binaryPath, paths.config, customSystemdExecStart)
      : platform === "launchd"
        ? renderLaunchdService(binaryPath, paths)
        : renderWindowsTaskDefinition(binaryPath, paths);
  writeServiceDefinition(paths.definition, definition);

  let code: number;
  if (platform === "systemd") {
    code = runCommand(["systemctl", "--user", "daemon-reload"]);
    if (code === 0) {
      code = runCommand(["systemctl", "--user", "enable", "shprd.service"]);
    }
    if (code === 0) {
      // `enable --now` does not restart an already-active service after its
      // definition changes. An explicit restart makes reinstall deterministic.
      code = runCommand(["systemctl", "--user", "restart", "shprd.service"]);
    }
  } else if (platform === "launchd") {
    const domain = `gui/${runtime.uid}`;
    const service = `${domain}/${SERVICE_LABEL}`;
    const loaded =
      runCommand(["launchctl", "print", service], { quiet: true }) === 0;
    if (loaded) {
      code = runCommand(["launchctl", "bootout", service]);
    } else {
      code = 0;
    }
    if (code === 0) {
      code = runCommand(["launchctl", "bootstrap", domain, paths.definition]);
    }
  } else {
    code = registerWindowsTask(paths.definition, runCommand);
    if (code === 0) {
      code = restartWindowsTask(windowsTaskName(paths), runCommand);
    }
  }

  if (code === 0) {
    log(`Installed ${platform} service: ${paths.definition}`);
    log(
      environmentCreated
        ? `Created service config: ${paths.config}`
        : `Preserved service config: ${paths.config}`,
    );
    if (customSystemdExecStart) {
      log(`Preserved custom ExecStart: ${customSystemdExecStart}`);
    }
    printServiceAccess(access, log);
  }
  return code;
}

function uninstallService(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  runCommand: RunCommand,
  log: (message: string) => void,
): number {
  const paths = resolveServicePaths(
    platform,
    runtime.homeDir,
    runtime.appDataDir,
  );
  const definitionExists = existsSync(paths.definition);
  if (!definitionExists && platform !== "windows-task") {
    log(`No managed ${platform} service found: ${paths.definition}`);
    log(`Preserved service config: ${paths.config}`);
    return 0;
  }
  if (
    definitionExists &&
    !readFileSync(paths.definition, "utf8").includes(GENERATED_MARKER) &&
    !readFileSync(paths.definition, "utf8").includes(LEGACY_GENERATED_MARKER)
  ) {
    throw new Error(
      `${paths.definition} was not generated by SHPRD and will not be removed`,
    );
  }
  if (platform === "systemd") {
    const stopCode = runCommand([
      "systemctl",
      "--user",
      "disable",
      "--now",
      "shprd.service",
    ]);
    if (stopCode !== 0) return stopCode;
    rmSync(paths.definition, { force: true });
    const code = runCommand(["systemctl", "--user", "daemon-reload"]);
    if (code !== 0) return code;
  } else if (platform === "launchd") {
    if (runtime.uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    const service = `gui/${runtime.uid}/${SERVICE_LABEL}`;
    const loaded =
      runCommand(["launchctl", "print", service], { quiet: true }) === 0;
    if (loaded) {
      const stopCode = runCommand(["launchctl", "bootout", service]);
      if (stopCode !== 0) return stopCode;
    }
    rmSync(paths.definition, { force: true });
  } else {
    const taskName = windowsTaskName(paths);
    const taskQuery = queryWindowsTask(taskName, runCommand);
    if (taskQuery.status === "error") return taskQuery.code;
    const taskExists = taskQuery.status === "exists";
    if (!definitionExists && !taskExists) {
      log(`No managed ${platform} service found: ${paths.definition}`);
      log(`Preserved service config: ${paths.config}`);
      return 0;
    }
    if (taskExists) {
      runCommand(["schtasks.exe", "/End", "/TN", taskName], {
        quiet: true,
      });
      const waitCode = waitForWindowsTaskStop(taskName, runCommand);
      if (waitCode !== 0) return waitCode;
      const deleteCode = runCommand([
        "schtasks.exe",
        "/Delete",
        "/TN",
        taskName,
        "/F",
      ]);
      if (deleteCode !== 0) {
        const afterDelete = queryWindowsTask(taskName, runCommand);
        if (afterDelete.status === "error") return afterDelete.code;
        if (afterDelete.status === "exists") return deleteCode;
      }
    }
    rmSync(paths.definition, { force: true });
  }
  log(`Removed ${platform} service: ${paths.definition}`);
  log(`Preserved service config: ${paths.config}`);
  return 0;
}

function runServiceAction(
  action: Exclude<ServiceAction, "install" | "uninstall">,
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  runCommand: RunCommand,
): number {
  if (action === "reload") {
    const paths = resolveServicePaths(
      platform,
      runtime.homeDir,
      runtime.appDataDir,
    );
    if (!existsSync(paths.definition)) {
      throw new Error(
        `cannot reload missing ${platform} service: ${paths.definition}`,
      );
    }
    if (platform === "systemd") {
      const reloadCode = runCommand(["systemctl", "--user", "daemon-reload"]);
      if (reloadCode !== 0) return reloadCode;
      return runCommand(["systemctl", "--user", "restart", "shprd.service"]);
    }
    if (platform === "windows-task") {
      const registerCode = registerWindowsTask(paths.definition, runCommand);
      return registerCode === 0
        ? restartWindowsTask(windowsTaskName(paths), runCommand)
        : registerCode;
    }
    if (runtime.uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    const domain = `gui/${runtime.uid}`;
    const service = `${domain}/${SERVICE_LABEL}`;
    const loaded =
      runCommand(["launchctl", "print", service], { quiet: true }) === 0;
    if (loaded) {
      const bootoutCode = runCommand(["launchctl", "bootout", service]);
      if (bootoutCode !== 0) return bootoutCode;
    }
    return runCommand(["launchctl", "bootstrap", domain, paths.definition]);
  }
  if (platform === "systemd") {
    return runCommand(
      action === "status"
        ? ["systemctl", "--user", "--no-pager", "status", "shprd.service"]
        : ["systemctl", "--user", "restart", "shprd.service"],
    );
  }
  if (platform === "windows-task") {
    const paths = resolveServicePaths(
      platform,
      runtime.homeDir,
      runtime.appDataDir,
    );
    const taskName = windowsTaskName(paths);
    return action === "status"
      ? runCommand([
          "schtasks.exe",
          "/Query",
          "/TN",
          taskName,
          "/V",
          "/FO",
          "LIST",
        ])
      : restartWindowsTask(taskName, runCommand);
  }
  if (runtime.uid === undefined) {
    throw new Error("cannot determine the current user id for launchd");
  }
  const service = `gui/${runtime.uid}/${SERVICE_LABEL}`;
  return runCommand(
    action === "status"
      ? ["launchctl", "print", service]
      : ["launchctl", "kickstart", "-k", service],
  );
}

export function runServiceCommand(
  args: string[],
  dependencies: ServiceCommandDependencies = {},
): number | null | typeof SERVICE_COMMAND_CONTINUE {
  const log = dependencies.log ?? console.log;
  const error = dependencies.error ?? console.error;
  let command: ParsedServiceCommand | null;
  try {
    const authTokenAction = parseAuthTokenCommand(args);
    if (authTokenAction) {
      const runtime = dependencies.runtime ?? {
        platform: process.platform,
        homeDir: homedir(),
        execPath: process.execPath,
        argv: process.argv,
      };
      const path = defaultAuthTokenPath(
        runtime.homeDir,
        runtime.platform,
        runtime.appDataDir,
        process.env.SHPRD_CONFIG_DIR ??
          legacyConfigDirForRuntime(runtime.execPath, runtime.homeDir) ??
          "",
      );
      log(authTokenAction === "show" ? loadOrCreateAuthToken(path) : path);
      return 0;
    }
    if (args[0] === "auth" && args[1] === "token") {
      log("Usage: shprd auth token <show|path>");
      return 0;
    }
    command = parseServiceCommand(args);
    if (!command) return null;
    if (command.action === "help") {
      log(serviceHelp());
      return 0;
    }
    if (command.action === "run") {
      const configPath = command.configPath ?? "";
      loadServiceEnvironmentFile(configPath);
      process.env.SHPRD_CONFIG_DIR ??= dirname(configPath);
      process.env.SHPRD_RESTART_SUPERVISOR = "1";
      return SERVICE_COMMAND_CONTINUE;
    }

    const runtime: ServiceRuntime = dependencies.runtime ?? {
      platform: process.platform,
      homeDir: homedir(),
      appDataDir: process.env.APPDATA,
      execPath: process.execPath,
      argv: process.argv,
      uid: process.getuid?.(),
    };
    const platform = resolveServicePlatform(runtime.platform);
    const runCommand = dependencies.runCommand ?? defaultRunCommand;
    if (command.action === "install") {
      return installService(
        platform,
        runtime,
        command.force,
        command.tailscaleMode,
        runCommand,
        dependencies.getTailscaleIPs ?? defaultTailscaleIPs,
        dependencies.isLegacyServiceActive ??
          (dependencies.runtime ? () => false : defaultIsLegacyServiceActive),
        log,
      );
    }
    if (command.action === "uninstall") {
      return uninstallService(platform, runtime, runCommand, log);
    }
    return runServiceAction(command.action, platform, runtime, runCommand);
  } catch (cause) {
    error(`shprd: ${(cause as Error).message}`);
    error(
      args[0] === "auth"
        ? "Run `shprd auth token --help` for usage."
        : "Run `shprd service --help` for usage.",
    );
    return 1;
  }
}
