import { afterEach, describe, expect, test } from "bun:test";
import {
  chmodSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { runServiceCommand, SERVICE_COMMAND_CONTINUE } from "./service-manager";
import {
  renderLaunchdService,
  renderSystemdService,
  renderWindowsTaskDefinition,
  resolveServicePaths,
} from "./service-definitions";

const tempDirs: string[] = [];

function tempHome(): string {
  const path = mkdtempSync(join(tmpdir(), "shprd-service-"));
  tempDirs.push(path);
  return path;
}

function isWindowsTaskQuery(argv: string[]): boolean {
  const script = argv.at(-1) ?? "";
  return (
    argv[0] === "powershell.exe" &&
    argv.includes("-Command") &&
    script.includes("CmdletizationQuery_NotFound_TaskName") &&
    script.includes("Out-Null")
  );
}

function isWindowsTaskWait(argv: string[]): boolean {
  const script = argv.at(-1) ?? "";
  return (
    argv[0] === "powershell.exe" &&
    argv.includes("-Command") &&
    script.includes("Get-ScheduledTask") &&
    script.includes("AddSeconds(15)")
  );
}

afterEach(() => {
  for (const path of tempDirs.splice(0)) {
    rmSync(path, { recursive: true, force: true });
  }
});

describe("service definition rendering", () => {
  test("escapes systemd paths without quoting them", () => {
    const definition = renderSystemdService(
      "/opt/Herdr % GUI/shprd",
      "/srv/herdr gui/config/shprd.env",
    );

    expect(definition).toContain(
      "EnvironmentFile=-/srv/herdr\\x20gui/config/shprd.env",
    );
    expect(definition).not.toContain('EnvironmentFile="');
    expect(definition).toContain("ExecStart=/opt/Herdr\\x20%%\\x20GUI/shprd");
    expect(definition).not.toContain('ExecStart="');
    expect(definition).toContain("Restart=always");
  });

  test("passes launchd paths as arguments without interpolating shell code", () => {
    const definition = renderLaunchdService("/Applications/Herdr & GUI", {
      config: "/srv/herdr & gui/config/shprd.env",
      definition: "/unused.plist",
      stdoutLog: "/srv/herdr & gui/logs/out.log",
      stderrLog: "/srv/herdr & gui/logs/error.log",
    });

    expect(definition).toContain(
      "<string>/Applications/Herdr &amp; GUI</string>",
    );
    expect(definition).toContain(
      "<string>/srv/herdr &amp; gui/config/shprd.env</string>",
    );
    expect(definition).toContain("<key>KeepAlive</key>");
    expect(definition).toContain("<key>SHPRD_RESTART_SUPERVISOR</key>");
    expect(definition).toContain("exec &quot;$2&quot;");
  });

  test("renders a direct-executable Windows login task", () => {
    const definition = renderWindowsTaskDefinition(
      "C:\\Program Files\\Herdr's GUI\\shprd.exe",
      {
        config: "C:\\Users\\tester\\AppData\\Roaming\\shprd\\shprd.env",
        definition: "C:\\unused.ps1",
        taskName: "dev.herdr.shprd-test-user",
      },
    );

    expect(definition.charCodeAt(0)).toBe(0xfeff);
    expect(definition).toContain(
      "New-ScheduledTaskAction -Execute 'C:\\Program Files\\Herdr''s GUI\\shprd.exe'",
    );
    expect(definition).toContain(
      'service run "C:\\Users\\tester\\AppData\\Roaming\\shprd\\shprd.env"',
    );
    expect(definition).toContain("$taskName = 'dev.herdr.shprd-test-user'");
    expect(definition).toContain("-AllowStartIfOnBatteries");
    expect(definition).toContain("Generated by SHPRD service install.");
  });

  test("isolates Windows task names by user config directory", () => {
    const first = resolveServicePaths(
      "windows-task",
      "C:\\Users\\first",
      "C:\\Users\\first\\AppData\\Roaming",
    );
    const second = resolveServicePaths(
      "windows-task",
      "C:\\Users\\second",
      "C:\\Users\\second\\AppData\\Roaming",
    );

    expect(first.taskName).toStartWith("dev.herdr.shprd-");
    expect(first.taskName).not.toBe(second.taskName);
  });
});

describe("service commands", () => {
  test("installs and starts a systemd user service", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const commands: Array<{ argv: string[]; quiet: boolean }> = [];
    const logs: string[] = [];
    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/opt/shprd-test/bin/shprd",
        argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
        uid: 1000,
      },
      runCommand: (argv, options) => {
        commands.push({ argv, quiet: options?.quiet === true });
        return 0;
      },
      getLanIPs: () => ["192.0.2.23"],
      log: (message) => logs.push(message),
    });

    expect(code).toBe(0);
    expect(commands).toEqual([
      {
        argv: ["systemctl", "--user", "daemon-reload"],
        quiet: false,
      },
      {
        argv: ["systemctl", "--user", "enable", "shprd.service"],
        quiet: false,
      },
      {
        argv: ["systemctl", "--user", "restart", "shprd.service"],
        quiet: false,
      },
    ]);
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "shprd.service",
    );
    const configPath = join(homeDir, ".config", "shprd", "shprd.env");
    expect(readFileSync(definitionPath, "utf8")).toContain(
      "ExecStart=/opt/shprd-test/bin/shprd",
    );
    expect(readFileSync(configPath, "utf8")).toContain("HOST=127.0.0.1");
    expect(statSync(configPath).mode & 0o777).toBe(0o600);
    expect(existsSync(join(homeDir, ".config", "shprd", "auth-token"))).toBe(
      false,
    );
    expect(logs.join("\n")).toContain("Installed systemd service");
    expect(logs.join("\n")).toContain(
      "Open: http://localhost:8787 (local access)",
    );
    expect(logs.join("\n")).not.toContain("Login token:");
  });

  test("installs a token-gated Tailnet service", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const logs: string[] = [];

    expect(
      runServiceCommand(["service", "install", "--tailscale"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/shprd-test/bin/shprd",
          argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
          uid: 1000,
        },
        runCommand: () => 0,
        getTailscaleIPs: () => ["100.85.194.64"],
        log: (message) => logs.push(message),
      }),
    ).toBe(0);

    const config = readFileSync(
      join(homeDir, ".config", "shprd", "shprd.env"),
      "utf8",
    );
    expect(config).toContain("HOST=100.85.194.64");
    expect(config).toContain("SHPRD_TAILSCALE_NO_AUTH=0");
    expect(logs.join("\n")).toContain("Tailnet URL: http://100.85.194.64:8787");
    expect(logs.join("\n")).toContain("shprd auth token show");
    expect(logs.join("\n")).not.toContain("Login token:");
  });

  test("installs an ACL-only Tailnet service only when explicitly requested", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const logs: string[] = [];

    expect(
      runServiceCommand(["service", "install", "--tailscale-no-auth"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/shprd-test/bin/shprd",
          argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
          uid: 1000,
        },
        runCommand: () => 0,
        getTailscaleIPs: () => ["100.85.194.64"],
        log: (message) => logs.push(message),
      }),
    ).toBe(0);

    const config = readFileSync(
      join(homeDir, ".config", "shprd", "shprd.env"),
      "utf8",
    );
    expect(config).toContain("HOST=100.85.194.64");
    expect(config).toContain("SHPRD_TAILSCALE_NO_AUTH=1");
    expect(logs.join("\n")).toContain("Tailnet ACLs control access");
    expect(logs.join("\n")).not.toContain("shprd auth token show");
  });

  test("resets a prior ACL-only Tailnet service on bare reinstall", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const configPath = join(homeDir, ".config", "shprd", "shprd.env");
    mkdirSync(dirname(configPath), { recursive: true });
    writeFileSync(
      configPath,
      "HOST=100.85.194.64\nSHPRD_TAILSCALE_NO_AUTH=1\n",
    );

    expect(
      runServiceCommand(["service", "install"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/shprd-test/bin/shprd",
          argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
          uid: 1000,
        },
        runCommand: () => 0,
        log: () => undefined,
      }),
    ).toBe(0);
    const config = readFileSync(configPath, "utf8");
    expect(config).toContain("HOST=127.0.0.1");
    expect(config).not.toContain("SHPRD_TAILSCALE_NO_AUTH");
  });

  test("normalizes duplicate environment assignments for an explicit Tailnet mode", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const configPath = join(homeDir, ".config", "shprd", "shprd.env");
    mkdirSync(dirname(configPath), { recursive: true });
    writeFileSync(
      configPath,
      "HOST=100.85.194.60\nSHPRD_TAILSCALE_NO_AUTH=0\nHOST=100.85.194.61\nSHPRD_TAILSCALE_NO_AUTH=1\n",
    );

    expect(
      runServiceCommand(["service", "install", "--tailscale"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/shprd-test/bin/shprd",
          argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
          uid: 1000,
        },
        runCommand: () => 0,
        getTailscaleIPs: () => ["100.85.194.64"],
        log: () => undefined,
      }),
    ).toBe(0);
    const config = readFileSync(configPath, "utf8");
    expect(config.match(/^HOST=/gm)).toHaveLength(1);
    expect(config.match(/^SHPRD_TAILSCALE_NO_AUTH=/gm)).toHaveLength(1);
    expect(config).toContain("HOST=100.85.194.64");
    expect(config).toContain("SHPRD_TAILSCALE_NO_AUTH=0");
  });

  test("blocks installation while a legacy systemd service definition exists", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const legacyPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "herdr-gui.service",
    );
    mkdirSync(dirname(legacyPath), { recursive: true });
    writeFileSync(
      legacyPath,
      "[Service]\nExecStart=/usr/local/bin/herdr-gui\n",
    );
    const errors: string[] = [];

    expect(
      runServiceCommand(["service", "install"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/shprd-test/bin/shprd",
          argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
          uid: 1000,
        },
        runCommand: () => 0,
        error: (message) => errors.push(message),
      }),
    ).toBe(1);
    expect(errors.join("\n")).toContain("legacy herdr-gui service exists");
    expect(existsSync(join(homeDir, ".config", "shprd", "shprd.env"))).toBe(
      false,
    );
  });

  test("blocks installation while a legacy service is active without its definition", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const errors: string[] = [];

    expect(
      runServiceCommand(["service", "install"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/shprd-test/bin/shprd",
          argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
          uid: 1000,
        },
        runCommand: () => 0,
        isLegacyServiceActive: () => true,
        error: (message) => errors.push(message),
      }),
    ).toBe(1);
    expect(errors.join("\n")).toContain("legacy herdr-gui service is active");
    expect(existsSync(join(homeDir, ".config", "shprd", "shprd.env"))).toBe(
      false,
    );
  });

  test("refuses a Tailnet install without one valid Tailnet IPv4", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const errors: string[] = [];

    expect(
      runServiceCommand(["service", "install", "--tailscale"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/shprd-test/bin/shprd",
          argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
          uid: 1000,
        },
        runCommand: () => 0,
        getTailscaleIPs: () => [],
        error: (message) => errors.push(message),
      }),
    ).toBe(1);
    expect(errors.join("\n")).toContain("one Tailnet IPv4");
    expect(existsSync(join(homeDir, ".config", "shprd", "shprd.env"))).toBe(
      false,
    );
  });

  test("refuses a Tailnet install with ambiguous Tailnet IPv4 addresses", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const errors: string[] = [];

    expect(
      runServiceCommand(["service", "install", "--tailscale"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/shprd-test/bin/shprd",
          argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
          uid: 1000,
        },
        runCommand: () => 0,
        getTailscaleIPs: () => ["100.85.194.64", "100.85.194.65"],
        error: (message) => errors.push(message),
      }),
    ).toBe(1);
    expect(errors.join("\n")).toContain("exactly one Tailnet IPv4");
  });

  test("reloads the systemd definition before restarting", () => {
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "shprd.service",
    );
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(definitionPath, "[Service]\nExecStart=/bin/true\n");
    const commands: string[][] = [];

    const code = runServiceCommand(["service", "reload"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/opt/shprd-test/bin/shprd",
        argv: ["/opt/shprd-test/bin/shprd", "service", "reload"],
      },
      runCommand: (argv) => {
        commands.push(argv);
        return 0;
      },
    });

    expect(code).toBe(0);
    expect(commands).toEqual([
      ["systemctl", "--user", "daemon-reload"],
      ["systemctl", "--user", "restart", "shprd.service"],
    ]);
  });

  test("does not restart systemd when daemon-reload fails", () => {
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "shprd.service",
    );
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(definitionPath, "[Service]\nExecStart=/bin/true\n");
    let commandCount = 0;

    const code = runServiceCommand(["service", "reload"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/opt/shprd-test/bin/shprd",
        argv: ["/opt/shprd-test/bin/shprd", "service", "reload"],
      },
      runCommand: () => {
        commandCount += 1;
        return 5;
      },
    });

    expect(code).toBe(5);
    expect(commandCount).toBe(1);
  });

  test("reports a missing service definition during reload", () => {
    const errors: string[] = [];
    let commandCount = 0;

    const code = runServiceCommand(["service", "reload"], {
      runtime: {
        platform: "linux",
        homeDir: tempHome(),
        execPath: "/opt/shprd-test/bin/shprd",
        argv: ["/opt/shprd-test/bin/shprd", "service", "reload"],
      },
      runCommand: () => {
        commandCount += 1;
        return 0;
      },
      error: (message) => errors.push(message),
    });

    expect(code).toBe(1);
    expect(commandCount).toBe(0);
    expect(errors.join("\n")).toContain(
      "cannot reload missing systemd service",
    );
  });

  test("preserves an existing environment file during reinstall", () => {
    const homeDir = tempHome();
    const configPath = join(homeDir, ".config", "shprd", "shprd.env");
    mkdirSync(join(homeDir, ".config", "shprd"), { recursive: true });
    writeFileSync(configPath, "HOST=0.0.0.0\nSHPRD_PASSWORD=secret\n");
    chmodSync(configPath, 0o644);

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/usr/local/bin/shprd",
        argv: ["/usr/local/bin/shprd", "service", "install"],
      },
      runCommand: () => 0,
      log: () => undefined,
    });

    expect(code).toBe(0);
    expect(readFileSync(configPath, "utf8")).toBe(
      "HOST=0.0.0.0\nSHPRD_PASSWORD=secret\n",
    );
    if (process.platform !== "win32") {
      expect(statSync(configPath).mode & 0o777).toBe(0o600);
    }
    expect(existsSync(join(homeDir, ".config", "shprd", "auth-token"))).toBe(
      false,
    );
  });

  test("preserves a managed custom wrapper command", () => {
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "shprd.service",
    );
    const binaryPath = join(homeDir, ".local", "bin", "shprd");
    const wrapperPath = join(homeDir, ".local", "libexec", "service-wrapper");
    const wrapperCommand =
      `${wrapperPath} --service example -- ` + `${binaryPath} --host 0.0.0.0`;
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(
      definitionPath,
      `# Generated by SHPRD service install.\n` +
        `[Service]\nExecStart=${wrapperCommand}\n`,
    );
    const logs: string[] = [];

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: binaryPath,
        argv: [binaryPath, "service", "install"],
      },
      runCommand: () => 0,
      getLanIPs: () => [],
      log: (message) => logs.push(message),
    });

    expect(code).toBe(0);
    const definition = readFileSync(definitionPath, "utf8");
    expect(definition).toContain(`ExecStart=${wrapperCommand}`);
    expect(definition).toContain("Restart=always");
    expect(logs).toContain(`Preserved custom ExecStart: ${wrapperCommand}`);
  });

  test("replaces a stale custom command that does not invoke this binary", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "shprd.service",
    );
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(
      definitionPath,
      `# Generated by SHPRD service install.\n` +
        `[Service]\n` +
        `ExecStart=/usr/local/bin/service-wrapper -- ` +
        `/opt/shprd-test/bin/shprd-old\n`,
    );

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/opt/shprd-test/bin/shprd",
        argv: ["/opt/shprd-test/bin/shprd", "service", "install"],
      },
      runCommand: () => 0,
      getLanIPs: () => [],
      log: () => undefined,
    });

    expect(code).toBe(0);
    expect(readFileSync(definitionPath, "utf8")).toContain(
      "ExecStart=/opt/shprd-test/bin/shprd",
    );
  });

  test("refuses to overwrite an unmanaged service without force", () => {
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "shprd.service",
    );
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(definitionPath, "[Service]\nExecStart=/custom/wrapper\n");
    const errors: string[] = [];
    let commandCount = 0;

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/usr/local/bin/shprd",
        argv: ["/usr/local/bin/shprd", "service", "install"],
      },
      runCommand: () => {
        commandCount += 1;
        return 0;
      },
      log: () => undefined,
      error: (message) => errors.push(message),
    });

    expect(code).toBe(1);
    expect(commandCount).toBe(0);
    expect(readFileSync(definitionPath, "utf8")).toContain("/custom/wrapper");
    expect(errors.join("\n")).toContain("rerun with --force");
  });

  test("validates launchd identity before writing service files", () => {
    const homeDir = tempHome();
    const errors: string[] = [];

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "darwin",
        homeDir,
        execPath: "/opt/shprd-test/bin/shprd",
        argv: ["/opt/shprd-test/bin/shprd"],
      },
      runCommand: () => {
        throw new Error("should not run");
      },
      error: (message) => errors.push(message),
    });

    expect(code).toBe(1);
    expect(errors.join("\n")).toContain(
      "cannot determine the current user id for launchd",
    );
    expect(() =>
      readFileSync(join(homeDir, ".config", "shprd", "shprd.env"), "utf8"),
    ).toThrow();
    expect(() =>
      readFileSync(
        join(homeDir, "Library", "LaunchAgents", "dev.herdr.shprd.plist"),
        "utf8",
      ),
    ).toThrow();
  });

  test("installs, inspects, restarts, reloads, and removes a launchd agent", () => {
    const homeDir = tempHome();
    const commands: Array<{ argv: string[]; quiet: boolean }> = [];
    const runtime = {
      platform: "darwin",
      homeDir,
      execPath: "/opt/shprd-test/bin/shprd",
      argv: ["/opt/shprd-test/bin/shprd"],
      uid: 501,
    };
    let launchdLoaded = false;
    const runCommand = (argv: string[], options?: { quiet?: boolean }) => {
      commands.push({ argv, quiet: options?.quiet === true });
      if (argv[1] === "print") return launchdLoaded ? 0 : 1;
      if (argv[1] === "bootstrap") launchdLoaded = true;
      if (argv[1] === "bootout") launchdLoaded = false;
      return 0;
    };

    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand,
        log: () => undefined,
      }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "status"], {
        runtime,
        runCommand,
      }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "restart"], {
        runtime,
        runCommand,
      }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "reload"], {
        runtime,
        runCommand,
      }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime,
        runCommand,
        log: () => undefined,
      }),
    ).toBe(0);

    const plistPath = join(
      homeDir,
      "Library",
      "LaunchAgents",
      "dev.herdr.shprd.plist",
    );
    expect(() => readFileSync(plistPath, "utf8")).toThrow();
    expect(commands).toEqual([
      {
        argv: ["launchctl", "print", "gui/501/dev.herdr.shprd"],
        quiet: true,
      },
      {
        argv: ["launchctl", "bootstrap", "gui/501", plistPath],
        quiet: false,
      },
      {
        argv: ["launchctl", "print", "gui/501/dev.herdr.shprd"],
        quiet: false,
      },
      {
        argv: ["launchctl", "kickstart", "-k", "gui/501/dev.herdr.shprd"],
        quiet: false,
      },
      {
        argv: ["launchctl", "print", "gui/501/dev.herdr.shprd"],
        quiet: true,
      },
      {
        argv: ["launchctl", "bootout", "gui/501/dev.herdr.shprd"],
        quiet: false,
      },
      {
        argv: ["launchctl", "bootstrap", "gui/501", plistPath],
        quiet: false,
      },
      {
        argv: ["launchctl", "print", "gui/501/dev.herdr.shprd"],
        quiet: true,
      },
      {
        argv: ["launchctl", "bootout", "gui/501/dev.herdr.shprd"],
        quiet: false,
      },
    ]);
    expect(
      readFileSync(join(homeDir, ".config", "shprd", "shprd.env"), "utf8"),
    ).toContain("HOST=127.0.0.1");
  });

  test("manages a Windows login task", () => {
    const homeDir = tempHome();
    const appDataDir = join(homeDir, "AppData", "Roaming");
    const executable = join(homeDir, "bin", "shprd.exe");
    const paths = resolveServicePaths("windows-task", homeDir, appDataDir);
    const definitionPath = paths.definition;
    const configPath = paths.config;
    const taskName = paths.taskName!;
    const runtime = {
      platform: "win32",
      homeDir,
      appDataDir,
      execPath: executable,
      argv: [executable],
    };
    const commands: Array<{ argv: string[]; quiet: boolean }> = [];
    let taskExists = false;
    const runCommand = (argv: string[], options?: { quiet?: boolean }) => {
      commands.push({ argv, quiet: options?.quiet === true });
      if (isWindowsTaskQuery(argv)) return taskExists ? 0 : 3;
      if (argv.includes("-File")) taskExists = true;
      if (argv[1] === "/Delete") taskExists = false;
      return 0;
    };

    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand,
        log: () => undefined,
      }),
    ).toBe(0);
    const definition = readFileSync(definitionPath, "utf8");
    expect(definition.charCodeAt(0)).toBe(0xfeff);
    expect(definition).toContain(
      `New-ScheduledTaskAction -Execute '${executable}'`,
    );
    expect(definition).toContain(`service run "${configPath}"`);
    expect(readFileSync(configPath, "utf8")).toContain("HOST=127.0.0.1");
    expect(existsSync(join(appDataDir, "shprd", "auth-token"))).toBe(false);

    expect(
      runServiceCommand(["service", "status"], { runtime, runCommand }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "restart"], { runtime, runCommand }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "reload"], { runtime, runCommand }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime,
        runCommand,
        log: () => undefined,
      }),
    ).toBe(0);

    expect(isWindowsTaskQuery(commands[0].argv)).toBeTrue();
    expect(commands[0].quiet).toBeFalse();
    expect(commands[0].argv.at(-1)).toContain(taskName);
    expect(commands.find(({ argv }) => argv.includes("-File"))?.argv).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      definitionPath,
    ]);
    expect(commands.filter(({ argv }) => argv.includes("-File"))).toHaveLength(
      2,
    );
    expect(commands.filter(({ argv }) => argv[1] === "/Run")).toHaveLength(3);
    expect(
      commands
        .filter(({ argv }) => argv.includes("/TN"))
        .every(({ argv }) => argv[argv.indexOf("/TN") + 1] === taskName),
    ).toBeTrue();
    expect(commands.some(({ argv }) => isWindowsTaskWait(argv))).toBeTrue();
    expect(commands.some(({ argv }) => argv[1] === "/Delete")).toBeTrue();
    expect(taskExists).toBeFalse();
    expect(existsSync(definitionPath)).toBeFalse();
    expect(existsSync(configPath)).toBeTrue();
  });

  test("uninstalls a Windows task when its helper script is missing", () => {
    const homeDir = tempHome();
    const appDataDir = join(homeDir, "AppData", "Roaming");
    const paths = resolveServicePaths("windows-task", homeDir, appDataDir);
    const taskName = paths.taskName!;
    const commands: string[][] = [];
    let taskExists = true;

    const code = runServiceCommand(["service", "uninstall"], {
      runtime: {
        platform: "win32",
        homeDir,
        appDataDir,
        execPath: join(homeDir, "shprd.exe"),
        argv: [],
      },
      runCommand: (argv) => {
        commands.push(argv);
        if (isWindowsTaskQuery(argv)) return taskExists ? 0 : 3;
        if (argv[1] === "/Delete") {
          taskExists = false;
          return 1;
        }
        return 0;
      },
      log: () => undefined,
    });

    expect(code).toBe(0);
    expect(commands.some((argv) => argv[1] === "/End")).toBeTrue();
    expect(commands.some((argv) => argv[1] === "/Delete")).toBeTrue();
    expect(commands.filter(isWindowsTaskQuery)).toHaveLength(2);
    expect(taskExists).toBeFalse();
    expect(existsSync(paths.definition)).toBeFalse();
    expect(
      commands
        .filter((argv) => argv.includes("/TN"))
        .every((argv) => argv[argv.indexOf("/TN") + 1] === taskName),
    ).toBeTrue();
  });

  test("removes a stale Windows helper when its task is already absent", () => {
    const homeDir = tempHome();
    const appDataDir = join(homeDir, "AppData", "Roaming");
    const paths = resolveServicePaths("windows-task", homeDir, appDataDir);
    mkdirSync(dirname(paths.definition), { recursive: true });
    writeFileSync(paths.definition, "# Generated by SHPRD service install.\n");
    const commands: string[][] = [];

    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime: {
          platform: "win32",
          homeDir,
          appDataDir,
          execPath: join(homeDir, "shprd.exe"),
          argv: [],
        },
        runCommand: (argv) => {
          commands.push(argv);
          return isWindowsTaskQuery(argv) ? 3 : 0;
        },
        log: () => undefined,
      }),
    ).toBe(0);

    expect(commands.filter(isWindowsTaskQuery)).toHaveLength(1);
    expect(commands.some((argv) => argv[1] === "/Delete")).toBeFalse();
    expect(existsSync(paths.definition)).toBeFalse();
  });

  test("propagates Windows task query failures without changing state", () => {
    const homeDir = tempHome();
    const appDataDir = join(homeDir, "AppData", "Roaming");
    const executable = join(homeDir, "shprd.exe");
    const paths = resolveServicePaths("windows-task", homeDir, appDataDir);
    const runtime = {
      platform: "win32",
      homeDir,
      appDataDir,
      execPath: executable,
      argv: [executable],
    };
    const installCommands: string[][] = [];

    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand: (argv) => {
          installCommands.push(argv);
          return isWindowsTaskQuery(argv) ? 5 : 0;
        },
        log: () => undefined,
      }),
    ).toBe(5);
    expect(installCommands).toHaveLength(1);
    expect(isWindowsTaskQuery(installCommands[0])).toBeTrue();
    expect(existsSync(paths.definition)).toBeFalse();
    expect(existsSync(paths.config)).toBeFalse();

    mkdirSync(dirname(paths.definition), { recursive: true });
    writeFileSync(paths.definition, "# Generated by SHPRD service install.\n");
    const uninstallCommands: string[][] = [];
    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime,
        runCommand: (argv) => {
          uninstallCommands.push(argv);
          return isWindowsTaskQuery(argv) ? 5 : 0;
        },
        log: () => undefined,
      }),
    ).toBe(5);
    expect(uninstallCommands).toHaveLength(1);
    expect(isWindowsTaskQuery(uninstallCommands[0])).toBeTrue();
    expect(existsSync(paths.definition)).toBeTrue();
  });

  test("does not restart when task-state confirmation fails", () => {
    const homeDir = tempHome();
    const executable = join(homeDir, "shprd.exe");
    const commands: string[][] = [];

    expect(
      runServiceCommand(["service", "restart"], {
        runtime: {
          platform: "win32",
          homeDir,
          appDataDir: join(homeDir, "AppData", "Roaming"),
          execPath: executable,
          argv: [executable],
        },
        runCommand: (argv) => {
          commands.push(argv);
          return isWindowsTaskWait(argv) ? 7 : 0;
        },
      }),
    ).toBe(7);
    expect(commands.some((argv) => argv[1] === "/End")).toBeTrue();
    expect(commands.some(isWindowsTaskWait)).toBeTrue();
    expect(commands.some((argv) => argv[1] === "/Run")).toBeFalse();
  });

  test("loads environment for the direct Windows task process", () => {
    const homeDir = tempHome();
    const configPath = join(homeDir, "shprd.env");
    writeFileSync(
      configPath,
      [
        "# service environment",
        "HOST=127.0.0.1",
        'export PORT="9123"',
        "HERDR_SESSION=gui-test",
      ].join("\n"),
    );
    const keys = [
      "HOST",
      "PORT",
      "HERDR_SESSION",
      "SHPRD_RESTART_SUPERVISOR",
    ] as const;
    const previous = new Map(keys.map((key) => [key, process.env[key]]));

    try {
      for (const key of keys) delete process.env[key];
      expect(runServiceCommand(["service", "run", configPath])).toBe(
        SERVICE_COMMAND_CONTINUE,
      );
      expect(process.env.HOST).toBe("127.0.0.1");
      expect(process.env.PORT).toBe("9123");
      expect(process.env.HERDR_SESSION).toBe("gui-test");
      expect(process.env.SHPRD_RESTART_SUPERVISOR).toBe("1");
    } finally {
      for (const [key, value] of previous) {
        if (value === undefined) delete process.env[key];
        else process.env[key] = value;
      }
    }
  });

  test("does not install a development runtime as a service", () => {
    const errors: string[] = [];
    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "darwin",
        homeDir: tempHome(),
        execPath: "/opt/homebrew/bin/bun",
        argv: ["/opt/homebrew/bin/bun", "src/index.ts", "service", "install"],
        uid: 501,
      },
      runCommand: () => {
        throw new Error("should not run");
      },
      error: (message) => errors.push(message),
    });

    expect(code).toBe(1);
    expect(errors.join("\n")).toContain(
      "service install requires the standalone shprd binary",
    );
  });

  test("does not bootstrap launchd when stopping the loaded job fails", () => {
    const homeDir = tempHome();
    const runtime = {
      platform: "darwin",
      homeDir,
      execPath: "/opt/shprd-test/bin/shprd",
      argv: ["/opt/shprd-test/bin/shprd"],
      uid: 501,
    };
    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand: (argv) => (argv[1] === "print" ? 1 : 0),
        log: () => undefined,
      }),
    ).toBe(0);

    let bootstrapCalled = false;
    const code = runServiceCommand(["service", "install"], {
      runtime,
      runCommand: (argv) => {
        if (argv[1] === "print") return 0;
        if (argv[1] === "bootout") return 5;
        if (argv[1] === "bootstrap") bootstrapCalled = true;
        return 0;
      },
      log: () => undefined,
    });

    expect(code).toBe(5);
    expect(bootstrapCalled).toBe(false);
  });

  test("keeps a managed systemd definition when stopping fails", () => {
    const homeDir = tempHome();
    const runtime = {
      platform: "linux",
      homeDir,
      execPath: "/opt/shprd-test/bin/shprd",
      argv: ["/opt/shprd-test/bin/shprd"],
    };
    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand: () => 0,
        log: () => undefined,
      }),
    ).toBe(0);

    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "shprd.service",
    );
    const code = runServiceCommand(["service", "uninstall"], {
      runtime,
      runCommand: (argv) => (argv.includes("disable") ? 1 : 0),
      log: () => undefined,
    });

    expect(code).toBe(1);
    expect(readFileSync(definitionPath, "utf8")).toContain(
      "Generated by SHPRD service install.",
    );
  });

  test("treats uninstall without a managed definition as a no-op", () => {
    let commandCount = 0;
    const logs: string[] = [];
    const code = runServiceCommand(["service", "uninstall"], {
      runtime: {
        platform: "linux",
        homeDir: tempHome(),
        execPath: "/opt/shprd-test/bin/shprd",
        argv: ["/opt/shprd-test/bin/shprd"],
      },
      runCommand: () => {
        commandCount += 1;
        return 0;
      },
      log: (message) => logs.push(message),
    });

    expect(code).toBe(0);
    expect(commandCount).toBe(0);
    expect(logs.join("\n")).toContain("No managed systemd service found");
  });
});
